The task request by the user is the following:
{task}

The actions already executed are the following:
{history}

The additional instructions for this step are the following:
{instructions}

You must answer using a properly json output containing in this order:
- your reasoning to pick this action
- the action you want to execute next and its parameters according to the JSON schema of the action

{format}