# .github/workflows/docker-build.yml
name: Build and Push Docker Image

on:
  workflow_dispatch:  # Only manual triggering
    inputs:
      version_override:
        description: 'Override version (leave empty to use .version file)'
        required: false
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          if [ -n "${{ github.event.inputs.version_override }}" ]; then
            echo "VERSION=${{ github.event.inputs.version_override }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=$(cat .version)" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            eschnou/opengpa-server:latest
            eschnou/opengpa-server:${{ steps.get_version.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=eschnou/opengpa-server:buildcache
          cache-to: type=registry,ref=eschnou/opengpa-server:buildcache,mode=max